name: Checks

on:
	pull_request:
		types:
			- opened
			- reopened
			- synchronize
		branches:
			- production

concurrency:
	group: checks-${{ github.ref }}
	cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Lint
        run: bun lint
      - name: Run Tests
        run: bun test
      - name: Build
        run: bun build
